in_images:
    T1w: '/project/6007967/akhanf/cfmm-bids/data/Khan/SNSX_7T/deriv/gradcorrect_0.0.1h/sub-{subject}/anat/sub-{subject}_acq-MP2RAGE_run-01_T1w.nii.gz'
    T2w: '/project/6007967/akhanf/cfmm-bids/data/Khan/SNSX_7T/deriv/prepT2space_v0.0.1f/sub-{subject}/anat/sub-{subject}_acq-SPACE_proc-prepT2_space-T1w_T2w.nii.gz'

participants_tsv: 'config/participants.tsv'

init_template:
    T1w: 'resources/tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz'
    T2w: 'resources/tpl-MNI152NLin2009cAsym_res-01_T2w.nii.gz'

max_iters: 4

#should be at least 2.3.1 (includes --random-seed option)
ants_container:  '/project/6007967/akhanf/singularity/ants-v2.3.1.sif'

ants:
    dim: 3
    random_seed: 42
    intensity_opts: '-u 1 -w [0.01,0.99] -z 1'
    linear:
        reg_iterations: '1000x500x250x0'
        shrink_factors: '6x4x2x1'
        smoothing_factors: '4x2x1x0'
    deform:
        shrink_factors: '12x6x4x2x1'  # default in antsMVTC2: 6x4x2x1 
        smoothing_factors: '6x3x2x1x0vox' # default in antsMVTC2: 3x2x1x0 
        reg_iterations: '100x100x70x50x10' # default in antsMVTC2: 100x100x70x20 
        transform_model: 'SyN[0.1,3,0]'
        sim_metric: CC
    shape_update:
        gradient_step: 0.25
